FROM debian:stable-slim

RUN apt update -y && apt upgrade -y

RUN apt install mosquitto mosquitto-clients -y

RUN echo "listner 1883 0.0.0.0" > 

# /home/fargus/Autamoted_home/Main_API/configs/mosquitto.conf:/mosquitto/config/mosquitto.conf